language: 
 - node_js

services: 
 - mongodb

node_js:
 - '7'
 - '9'

install:
 - npm install
 - npm install --only=dev
 - npm install codecov nyc -g

before_script:
 - make conf
 - sleep 1

script:
 - nyc mocha

after_success:
 - codecov -f ./coverage/coverage-final.json
